// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ElHLZflbhYf5Xxhjmw75JNdqsKM5BHo',
    appId: '1:452434406713:web:02bb454487f8d3ffcf4ce8',
    messagingSenderId: '452434406713',
    projectId: 'proyecto2-f0257',
    authDomain: 'proyecto2-f0257.firebaseapp.com',
    storageBucket: 'proyecto2-f0257.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA42hpkkHP6TvYr1h5nzM3P22DSGfx3a74',
    appId: '1:452434406713:android:2c6532965f38696ecf4ce8',
    messagingSenderId: '452434406713',
    projectId: 'proyecto2-f0257',
    storageBucket: 'proyecto2-f0257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXVDNo-TdkwnlA_bdLcrOP7i0zHifgHPc',
    appId: '1:452434406713:ios:f0f564b5c8b3c03bcf4ce8',
    messagingSenderId: '452434406713',
    projectId: 'proyecto2-f0257',
    storageBucket: 'proyecto2-f0257.appspot.com',
    iosClientId: '452434406713-11mu899296hpb6kvnd1eqjfta28uh8qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto218401120',
  );
}
